sudo: false
language: java
jdk:
- openjdk8
cache:
  directories:
  - "$HOME/.m2/repository"
notifications:
  email:
    on_success: never
    on_failure: never
  slack:
    on_success: never
    on_failure: always
branches:
  only:
  - master
  - development
install: true
script: "chmod +x .travis.sh && ./.travis.sh pom.xml && ./.travis.sh cli/pom.xml && ./.travis.sh portal/pom.xml && ./.travis.sh portal/portlet/pom.xml"
env:
  global:
  - secure: ZruVrOJT1r4pXcESg6lldRsQUBexPCHb1joqSS7TQglLW8UQ/uV6utpIrb98RuHoy2x91KqGtkihCnkRmwHPEfFICKqUcYntIroRGLhC3aC6iRKjsbxNF1XLwn8pUNQfRk193eB3KBLUUSoiPTMKwqfbUk5McPmgGlzM5fTx8CJgdOddJzhB1WzW+L98+CKeWMTYZkaDsCASsMzM23faWLCHEjAGJRgFaeoinUxWALq1+zSuHFWevm4kDEXMJyoIw/e7OibkhmjDZF3r7e0xbTqWU/qZCwu+9jLKwaBnUD6usVWQQT1mEjvmT3D75HS0oy9AThtsbIYC3E5KdbJEg4tEH80mTSFFLN+mbTFiCwfny3u87xxK+uriV2QhUskxp3wXZ8TbNv7S6ygb0uLbmrgSD0j1likwG2NTUTDNe09yYbBOiIWAZ4LNGvgpqfMHsmbuLCjBpEhGJk57CzvtryL1yFqhWwxHgdc5Z4mYV8gN9jr64xOUKYpiu4Zbg8UHfEtxggXkkukQrson5A0c2DCubDZtLFTZMDjSOuw3RSXhotF92k0OfBLFI0wRmeKpMSud+1Etswhqv3x188TDlzUDHkk5nEMWfQBlnQP6L3DFlcznpt5wwGKgJGtsXwtHUq3iaRn84C+B7zw8IvK5tlp0mQM6lgh9v29tY5581BY=
  - secure: JwX9bFlvHv92WM2RBPmRdKvZjExXGuLenCxKDVm1qDjMkmA6mCoxEOX2fuY9DAadzQhcjuTwYxhigkVGwWQttfr8ovyhkrMxDzRTSo4wlFlogeg80U3lkEpgkZrhxz3LizFAG6FdYHP3egHJZLtr72NLybzug4FPB3OFPP7ts+3lUcVV+PL1qCRFI0xW6m5g+WExjqSUD8T00p4VO/OfaNqiY1x/u+4cwAVkX+OvmiWssfBIK2HLpCerGJkJIWKX980S+m3+BeB8hmhovaghFRHqSdu8oxIYCzw+3rbywdezl9a8Xj+SBzNnDdKS9b6KP9k9JnA0f4LPieH/x1I2L+hu5D+lH/q0WNTO8mH9Bqrg19cAiZy+50plwRfKp2IOz4qoStBjAEYviulLEUuUhcfNk1yeYp3MLA7/OK2pOmXC/m0+wJFFl0URO37PiClpa1AAFFuAre6Fo7Apld2rlJUkCmR1FrQl1Zy7/S0wPShotzivKxQhfvIywcrDzwJ6qSWcIomYHnT8rnoW1Y/Pe6yl03DepcfNf7f+KeW2IBsJFz2VeVbBkFj03XW5nzf7RVpV0/pXOPEaArAvlB23mQsdiZGXSzp+P3J21wEMBSII+XD1FiXB5JBK0TQcJa4gpzh2CzNuC5te8qorY/MEd4o/9BU2bhPRa8sMSa9j+KM=
